{/* <Animated.View style={{
    width:100,height:100,
    backgroundColor:'red',
    borderRadius:100/2,
    opacity:translation,
  }}
  /> */}
//   <Text>
//     kuch Value
//     <Text>kuch aur</Text>
//   </Text>
//   <Animated.Text
//     style={{
//       color: '#22ff',
//       fontSize: 20,
//       opacity: translation,
//       transform: [{translateX: translation}],
//     }}>
//      {text}
//       {translation.toValue == 100 ? (alert('full')):null}
 
//   </Animated.Text>
//   <TouchableOpacity onPress={MyAnimation}>
//     <Text>touch</Text>
//   </TouchableOpacity>
  {/* <TouchableOpacity onPress={MyAnimation2}>
    <Text>release</Text>
  </TouchableOpacity> */}